{{- if and ((.Values.gitproxy).enabled) .Values.gitproxy.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: gitproxy-ca
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
type: Opaque
stringData:
  ca.crt: |-
    {{- .Values.gitproxy.caCert | nindent 4 }}
{{- end }}
