{{- if .Values.gitproxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitproxy
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
data:
  WITH_TELEMETRY: "true"
  LOG_FILE_PATH: {{ printf "%s/gitproxy.log" (include "logging.dir" .) | quote }}
{{- end }}
