{{- if not (lookup "v1" "Secret" (default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-") (include "secretname.langfuse" . | trimAll "\"")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretname.langfuse" . }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
type: Opaque
stringData:
  LANGFUSE_ENDPOINT: "http://localhost:0"
  LANGFUSE_BASIC_AUTH: ""
  LANGFUSE_TLS_INSECURE: "true"
  LANGFUSE_TIMEOUT: "30s"
{{- end }}
